/* DO NOT EDIT THIS FILE - it is machine generated */
#include <com_example_mytest_JniTest.h>
/* Header for class com_example_mytest_JniTest */


/*
 * Class:     com_example_mytest_JniTest
 * Method:    testxu
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_mytest_JniTest_testxu
  (JNIEnv *env, jobject jobj)
  {
  return (*env)->NewStringUTF(env,"This just a test for Android Studio NDK JNI developer!");
  }


