/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mytest_JniTest */

#ifndef _Included_com_example_mytest_JniTest
#define _Included_com_example_mytest_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mytest_JniTest
 * Method:    testxu
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_mytest_JniTest_testxu
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
